FluentSettings.LoadMappingProfile<ReportRow, ReportRowProfile>();

var list = new List<ReportRow>
{
    new ReportRow { Id = 1, Name = "Alice", Amount = 1500.50m, Status = "Approved", Date = DateTime.Now.AddDays(-10) },
    new ReportRow { Id = 2, Name = "Bob", Amount = -200.75m, Status = "Pending", Date = DateTime.Now.AddDays(-5) },
    new ReportRow { Id = 3, Name = "Charlie", Amount = 300.00m, Status = "Rejected", Date = DateTime.Now.AddDays(-2) },
    new ReportRow { Id = 4, Name = "Diana", Amount = 450.25m, Status = "Approved", Date = DateTime.Now.AddDays(-1) },
};

const string path = @"C:\Users\Weiha\Downloads\test\report.xlsx";
list.ToExcelFile(path);
Console.WriteLine($"Excel file generated at: {path}");

public class ReportRow
{
    public int Id { get; set; }
    public required string Name { get; set; }
    public decimal Amount { get; set; }
    public required string Status { get; set; }
    public DateTime Date { get; set; }
}

public class ReportRowProfile : IMappingProfile<ReportRow>
{
    public void Configure(IExcelConfiguration<ReportRow> configuration)
    {
        configuration.HasAuthor("Spark")
            .HasTitle("OpenXML Report")
            .HasDescription("Report generated by Spark.OpenXml");

        configuration.HasSheetSetting(config =>
        {
            config.SheetName = "Report";
            config.StartRowIndex = 0;
            config.AutoColumnWidthEnabled = true;
        });

        configuration.Property(x => x.Id).HasColumnIndex(0);
        configuration.Property(x => x.Name).HasColumnIndex(1);
        configuration.Property(x => x.Amount).HasColumnIndex(2);
        configuration.Property(x => x.Status).HasColumnIndex(3);
        configuration.Property(x => x.Date)
            .HasColumnIndex(4)
            .HasColumnFormatter("yyyy-MM-dd");
    }
}
